import 'package:flutter/widgets.dart';

@staticIconProvider
abstract class Brandico {
  static const IconData facebook = IconData(62208, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData facebook_rect = IconData(62209, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData twitter = IconData(62210, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData twitter_bird = IconData(62211, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData vimeo = IconData(62223, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData vimeo_rect = IconData(62222, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData tumblr = IconData(62225, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData tumblr_rect = IconData(62224, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData googleplus_rect = IconData(62217, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData github_text = IconData(62215, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData github = IconData(62216, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData skype = IconData(62219, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData icq = IconData(62212, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData yandex = IconData(62213, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData yandex_rect = IconData(62214, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData vkontakte_rect = IconData(62218, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData odnoklassniki = IconData(62220, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData odnoklassniki_rect = IconData(62221, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData friendfeed = IconData(62226, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData friendfeed_rect = IconData(62227, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData blogger = IconData(62228, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData blogger_rect = IconData(62229, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData deviantart = IconData(62230, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData jabber = IconData(62231, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData lastfm = IconData(62232, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData lastfm_rect = IconData(62233, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData linkedin = IconData(62234, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData linkedin_rect = IconData(62235, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData picasa = IconData(62236, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData wordpress = IconData(62237, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData instagram = IconData(62238, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData instagram_filled = IconData(62239, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData diigo = IconData(62240, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData box = IconData(62241, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData box_rect = IconData(62242, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData tudou = IconData(62243, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData youku = IconData(62244, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData win8 = IconData(62245, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData amex = IconData(62246, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData discover = IconData(62247, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData visa = IconData(62248, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData mastercard = IconData(62249, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData houzz = IconData(62250, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData bandcamp = IconData(62251, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData codepen = IconData(62252, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
}
