import 'package:flutter/material.dart';

class Brandico {
  Brandico._();

  static const IconData facebook = const IconData(62208, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData facebook_rect = const IconData(62209, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData twitter = const IconData(62210, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData twitter_bird = const IconData(62211, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData vimeo = const IconData(62223, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData vimeo_rect = const IconData(62222, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData tumblr = const IconData(62225, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData tumblr_rect = const IconData(62224, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData googleplus_rect = const IconData(62217, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData github_text = const IconData(62215, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData github = const IconData(62216, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData skype = const IconData(62219, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData icq = const IconData(62212, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData yandex = const IconData(62213, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData yandex_rect = const IconData(62214, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData vkontakte_rect = const IconData(62218, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData odnoklassniki = const IconData(62220, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData odnoklassniki_rect = const IconData(62221, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData friendfeed = const IconData(62226, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData friendfeed_rect = const IconData(62227, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData blogger = const IconData(62228, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData blogger_rect = const IconData(62229, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData deviantart = const IconData(62230, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData jabber = const IconData(62231, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData lastfm = const IconData(62232, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData lastfm_rect = const IconData(62233, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData linkedin = const IconData(62234, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData linkedin_rect = const IconData(62235, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData picasa = const IconData(62236, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData wordpress = const IconData(62237, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData instagram = const IconData(62238, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData instagram_filled = const IconData(62239, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData diigo = const IconData(62240, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData box = const IconData(62241, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData box_rect = const IconData(62242, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData tudou = const IconData(62243, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData youku = const IconData(62244, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData win8 = const IconData(62245, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData amex = const IconData(62246, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData discover = const IconData(62247, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData visa = const IconData(62248, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData mastercard = const IconData(62249, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData houzz = const IconData(62250, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData bandcamp = const IconData(62251, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
  static const IconData codepen = const IconData(62252, fontFamily: 'Brandico', fontPackage: 'flutter_icons');
}
