import 'package:flutter/widgets.dart';

@staticIconProvider
abstract class Linecons {
  static const IconData music = IconData(57378, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData search = IconData(57353, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData mail = IconData(57369, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData heart = IconData(57344, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData star = IconData(57346, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData user = IconData(57351, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData videocam = IconData(57349, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData camera = IconData(57355, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData photo = IconData(57371, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData attach = IconData(57385, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData lock = IconData(57357, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData eye = IconData(57363, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData tag = IconData(57356, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData thumbs_up = IconData(57370, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData pencil = IconData(57359, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData comment = IconData(57364, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData location = IconData(57362, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData cup = IconData(57366, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData trash = IconData(57350, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData doc = IconData(57368, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData note = IconData(57372, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData cog = IconData(57354, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData params = IconData(57375, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData calendar = IconData(57387, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData sound = IconData(57348, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData clock = IconData(57373, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData lightbulb = IconData(57358, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData tv = IconData(57347, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData desktop = IconData(57361, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData mobile = IconData(57367, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData cd = IconData(57389, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData inbox = IconData(57365, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData globe = IconData(57391, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData cloud = IconData(57345, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData paper_plane = IconData(57374, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData fire = IconData(57384, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData graduation_cap = IconData(57380, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData megaphone = IconData(57379, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData database = IconData(57377, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData key = IconData(57352, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData beaker = IconData(57381, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData truck = IconData(57390, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData money = IconData(57376, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData food = IconData(57382, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData shop = IconData(57386, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData diamond = IconData(57360, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData t_shirt = IconData(57383, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData wallet = IconData(57388, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
}
