import 'package:flutter/material.dart';

class Linecons {
  Linecons._();

  static const IconData music = const IconData(57378, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData search = const IconData(57353, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData mail = const IconData(57369, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData heart = const IconData(57344, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData star = const IconData(57346, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData user = const IconData(57351, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData videocam = const IconData(57349, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData camera = const IconData(57355, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData photo = const IconData(57371, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData attach = const IconData(57385, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData lock = const IconData(57357, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData eye = const IconData(57363, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData tag = const IconData(57356, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData thumbs_up = const IconData(57370, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData pencil = const IconData(57359, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData comment = const IconData(57364, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData location = const IconData(57362, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData cup = const IconData(57366, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData trash = const IconData(57350, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData doc = const IconData(57368, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData note = const IconData(57372, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData cog = const IconData(57354, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData params = const IconData(57375, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData calendar = const IconData(57387, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData sound = const IconData(57348, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData clock = const IconData(57373, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData lightbulb = const IconData(57358, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData tv = const IconData(57347, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData desktop = const IconData(57361, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData mobile = const IconData(57367, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData cd = const IconData(57389, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData inbox = const IconData(57365, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData globe = const IconData(57391, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData cloud = const IconData(57345, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData paper_plane = const IconData(57374, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData fire = const IconData(57384, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData graduation_cap = const IconData(57380, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData megaphone = const IconData(57379, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData database = const IconData(57377, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData key = const IconData(57352, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData beaker = const IconData(57381, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData truck = const IconData(57390, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData money = const IconData(57376, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData food = const IconData(57382, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData shop = const IconData(57386, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData diamond = const IconData(57360, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData t_shirt = const IconData(57383, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
  static const IconData wallet = const IconData(57388, fontFamily: 'Linecons', fontPackage: 'flutter_icons');
}
