import 'package:flutter/material.dart';

class Meteocons {
  Meteocons._();

  static const IconData windy_rain_inv = const IconData(59392, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow_inv = const IconData(59393, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow_heavy_inv = const IconData(59394, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData hail_inv = const IconData(59395, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds_inv = const IconData(59396, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds_flash_inv = const IconData(59397, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData temperature = const IconData(59398, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData compass = const IconData(59399, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData na = const IconData(59400, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fahrenheit = const IconData(59401, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds_flash_alt = const IconData(59402, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData sun_inv = const IconData(59403, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData moon_inv = const IconData(59404, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_sun_inv = const IconData(59405, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_moon_inv = const IconData(59406, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_inv = const IconData(59407, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_flash_inv = const IconData(59408, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData drizzle_inv = const IconData(59409, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData rain_inv = const IconData(59410, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData windy_inv = const IconData(59411, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData sunrise = const IconData(59412, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData sun = const IconData(59413, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData moon = const IconData(59414, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData eclipse = const IconData(59415, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData mist = const IconData(59416, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData wind = const IconData(59417, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snowflake = const IconData(59418, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_sun = const IconData(59419, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_moon = const IconData(59420, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fog_sun = const IconData(59421, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fog_moon = const IconData(59422, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fog_cloud = const IconData(59423, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fog = const IconData(59424, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud = const IconData(59425, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_flash = const IconData(59426, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_flash_alt = const IconData(59427, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData drizzle = const IconData(59428, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData rain = const IconData(59429, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData windy = const IconData(59430, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData windy_rain = const IconData(59431, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow = const IconData(59432, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow_alt = const IconData(59433, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow_heavy = const IconData(59434, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData hail = const IconData(59435, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds = const IconData(59436, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds_flash = const IconData(59437, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
}
