import 'package:flutter/widgets.dart';

@staticIconProvider
abstract class Meteocons {
  static const IconData windy_rain_inv = IconData(59392, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow_inv = IconData(59393, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow_heavy_inv = IconData(59394, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData hail_inv = IconData(59395, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds_inv = IconData(59396, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds_flash_inv = IconData(59397, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData temperature = IconData(59398, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData compass = IconData(59399, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData na = IconData(59400, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fahrenheit = IconData(59401, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds_flash_alt = IconData(59402, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData sun_inv = IconData(59403, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData moon_inv = IconData(59404, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_sun_inv = IconData(59405, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_moon_inv = IconData(59406, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_inv = IconData(59407, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_flash_inv = IconData(59408, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData drizzle_inv = IconData(59409, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData rain_inv = IconData(59410, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData windy_inv = IconData(59411, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData sunrise = IconData(59412, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData sun = IconData(59413, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData moon = IconData(59414, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData eclipse = IconData(59415, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData mist = IconData(59416, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData wind = IconData(59417, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snowflake = IconData(59418, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_sun = IconData(59419, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_moon = IconData(59420, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fog_sun = IconData(59421, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fog_moon = IconData(59422, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fog_cloud = IconData(59423, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData fog = IconData(59424, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud = IconData(59425, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_flash = IconData(59426, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData cloud_flash_alt = IconData(59427, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData drizzle = IconData(59428, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData rain = IconData(59429, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData windy = IconData(59430, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData windy_rain = IconData(59431, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow = IconData(59432, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow_alt = IconData(59433, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData snow_heavy = IconData(59434, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData hail = IconData(59435, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds = IconData(59436, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
  static const IconData clouds_flash = IconData(59437, fontFamily: 'Meteocons', fontPackage: 'flutter_icons');
}
